name: Build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  USERNAME: 1715142548
  PASSWORD: wxl5211314
  # github.repository as <account>/<repo>
  IMAGE_NAME: 1715142548/PHproject/exam

  #DOCKERHUB_TOKEN: dckr_pat_wgZq0KEbbeDRaDV5LwRTuLAkCjM
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Checkout allParent
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/allParent
          path: allParent
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout data
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/data
          path: data
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout base
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/base
          path: base
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout gateway
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/gateway
          path: gateway
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout illness
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/illness
          path: illness
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout user
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/user
          path: user
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout exam
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/exam
          path: exam
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout utils
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/utils
          path: utils
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout feign
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/feign
          path: feign
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build allParent with Maven
        run: mvn clean install
        working-directory: allParent

      - name: Build utils with Maven
        run: mvn clean install
        working-directory: utils

      - name: Build feign with Maven
        run: mvn clean install
        working-directory: feign

      - name: Build final jar
        run: mvn clean package
        working-directory: exam

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./exam/Dockerfile