name: Build

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: docker.io
  USERNAME: 1715142548
  PASSWORD: wxl5211314
  TARGET_MODULE: exam
  IMAGE_NAME: 1715142548/pet-hospital-exam
  # 服务器root密码
  ROOT_PASSWORD: Wxl5211314.0.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout allParent
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/allParent
          path: allParent
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout data
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/data
          path: data
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout base
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/base
          path: base
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout gateway
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/gateway
          path: gateway
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout illness
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/illness
          path: illness
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout user
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/user
          path: user
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout exam
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/exam
          path: exam
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout utils
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/utils
          path: utils
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Checkout feign
        uses: actions/checkout@v2
        with:
          repository: SDP-Gang-of-Six/feign
          path: feign
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build allParent with Maven
        run: mvn clean install
        working-directory: allParent

      - name: Build final ${{ env.TARGET_MODULE }} jar
        run: mvn clean package
        working-directory: ${{ env.TARGET_MODULE }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ${{ env.TARGET_MODULE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./${{ env.TARGET_MODULE }}/Dockerfile

      - name: Run command via SSH
        run: sshpass -p "${{ env.ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@wxl475.cn "sh /root/pet-hospital/${{ env.TARGET_MODULE }}.sh"